font_family family="SauceCodePro Nerd Font"
font_size 16.0
auto_reload_config -1

foreground #e6e6e6
background #1e1f29
cursor #bbbbbb
cursor_text_color #ffffff
selection_foreground #ffffff
selection_background #44475a

color0 #000000
color1 #ff5555
color2 #50fa7b
color3 #f1fa8c
color4 #bd93f9
color5 #ff79c6
color6 #8be9fd
color7 #bbbbbb
color8 #555555
color9 #ff5555
color10 #50fa7b
color11 #f1fa8c
color12 #bd93f9
color13 #ff79c6
color14 #8be9fd
color15 #ffffff

include power-mode.conf

background_opacity 1.0
dynamic_background_opacity no
macos_titlebar_color background
hide_window_decorations titlebar-only
macos_show_window_title_in none
window_padding_width 0
window_margin_width 0
remember_window_size yes

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_bar_min_tabs 2
tab_title_template "{sup.index} {title}"
tab_activity_symbol " ●"
active_tab_foreground #1e1f29
active_tab_background #b294bb
active_tab_font_style bold
inactive_tab_foreground #e6e6e6
inactive_tab_background #232530
inactive_tab_font_style normal
tab_bar_background #1e1f29
tab_bar_margin_color #1e1f29

close_on_child_death yes
shell_integration no-cursor
macos_option_as_alt both
allow_remote_control no

repaint_delay 10
input_delay 3
sync_to_monitor yes

map super+1
map super+2
map super+3
map super+4
map super+5
map super+6
map super+7
map super+8
map super+9
map super+t
map ctrl+shift+p
map ctrl+shift+t
map ctrl+shift+q
map ctrl+shift+v
map ctrl+shift+enter

map super+1 goto_tab 1
map super+2 goto_tab 2
map super+3 goto_tab 3
map super+4 goto_tab 4
map super+5 goto_tab 5
map super+6 goto_tab 6
map super+7 goto_tab 7
map super+8 goto_tab 8
map super+9 goto_tab 999
map super+t new_tab_with_cwd

map ctrl+1 send_text all \x1b[49;5u
map ctrl+2 send_text all \x1b[50;5u
map ctrl+3 send_text all \x1b[51;5u
map ctrl+4 send_text all \x1b[52;5u
map ctrl+5 send_text all \x1b[53;5u
map ctrl+6 send_text all \x1b[54;5u
map ctrl+7 send_text all \x1b[55;5u
map ctrl+8 send_text all \x1b[56;5u
map ctrl+9 send_text all \x1b[57;5u

map alt+shift+n send_text all \x1b[78;3u
map alt+shift+e send_text all \x1b[69;3u
map alt+shift+u send_text all \x1b[85;3u
map alt+shift+i send_text all \x1b[73;3u
map alt+shift+q send_text all \x1b[81;3u
map ctrl+shift+v send_text all \x1b[118;6u
map ctrl+shift+l send_text all \x1b[108;6u
map ctrl+shift+y send_text all \x1b[121;6u

mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link
