source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh



if [ -f ~/.sconfig/zsh/zshrc ]; then
	source ~/.sconfig/zsh/zshrc
fi

autopair-init

